
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 39121742018.1
 */
public class TelaUrna extends javax.swing.JFrame {

    /**
     * Creates new form TelaUrna
     */
    public TelaUrna() {
        initComponents();
       PanObrigatorio.setVisible(false);
         PanOpcional.setVisible(false);
        PanProibido.setVisible(false);
        Painel_inicial.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        Painel_Vazio = new javax.swing.JPanel();
        Painel_inicial = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nascimento = new javax.swing.JLabel();
        campo_idade = new javax.swing.JTextField();
        cortina = new javax.swing.JPanel();
        PanObrigatorio = new javax.swing.JPanel();
        lbl_obrigatorio = new javax.swing.JLabel();
        PanProibido = new javax.swing.JPanel();
        lbl_voto_proibido = new javax.swing.JLabel();
        PanOpcional = new javax.swing.JPanel();
        lbl_voto_opcional = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Java - Aula 10 - 1 Estruturas Condicionais Parte 2 - Botão Confirmar.png"))); // NOI18N
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 80, 60));

        Painel_Vazio.setBackground(new java.awt.Color(204, 204, 204));
        Painel_Vazio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel_inicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Verificação do direito de voto.");
        Painel_inicial.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 11, 480, -1));

        lbl_nascimento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbl_nascimento.setText("Data de Nasciemnto");
        Painel_inicial.add(lbl_nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 98, -1, -1));

        campo_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_idadeActionPerformed(evt);
            }
        });
        Painel_inicial.add(campo_idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 81, 50, -1));

        Painel_Vazio.add(Painel_inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 140));

        cortina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanObrigatorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_obrigatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Java - Aula 10 - 1 Estruturas Condicionais Parte 2 - Voto Obrigatório.png"))); // NOI18N
        PanObrigatorio.add(lbl_obrigatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 90));

        cortina.add(PanObrigatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 260));

        PanProibido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_voto_proibido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Java - Aula 10 - 1 Estruturas Condicionais Parte 2 - Voto Proibido.png"))); // NOI18N
        PanProibido.add(lbl_voto_proibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 100));

        cortina.add(PanProibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 190));

        PanOpcional.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_voto_opcional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Java - Aula 10 - 1 Estruturas Condicionais Parte 2 - Voto Opcional.png"))); // NOI18N
        PanOpcional.add(lbl_voto_opcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 90));

        cortina.add(PanOpcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Painel_Vazio.add(cortina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 550, 180));

        getContentPane().add(Painel_Vazio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 550, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Java - Aula 10 - 1 Estruturas Condicionais Parte 2 - Urna Eletrônica.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        //Variáveis
        int nasc = Integer.parseInt(campo_idade.getText());
        //Date hora = new Date();
        //SimpleDateFormat formatador = new SimpleDateFormat("yyyy");
        //int ano = Integer.parseInt(formatador.format(hora));
        //calculos
        int an = Integer.parseInt(campo_idade.getText());
        int ano = Calendar.getInstance().get(Calendar.YEAR);
        int idade = ano - nasc;
        
        //saídas
        /*if (idade>=16 && idade <18){
            PanObrigatorio.setVisible(false);
            PanOpcional.setVisible(true);
            PanProibido.setVisible(false);
        }if (idade>=18 && idade <71) {
            
        }else{
            PanObrigatorio.setVisible(false);
            PanOpcional.setVisible(false);
            PanProibido.setVisible(true);
        }*/
        
        if (idade < 16 || idade >71){
            PanObrigatorio.setVisible(false);
            PanOpcional.setVisible(false);
            PanProibido.setVisible(true);
        }else{
            if (idade>=16 && idade <18){
                PanObrigatorio.setVisible(false);
                PanOpcional.setVisible(true);
                PanProibido.setVisible(false);
            }else{
                PanObrigatorio.setVisible(true);
                PanOpcional.setVisible(false);
                PanProibido.setVisible(false);
            }
        }
        
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void campo_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_idadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUrna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Vazio;
    private javax.swing.JPanel Painel_inicial;
    private javax.swing.JPanel PanObrigatorio;
    private javax.swing.JPanel PanOpcional;
    private javax.swing.JPanel PanProibido;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JTextField campo_idade;
    private javax.swing.JPanel cortina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_nascimento;
    private javax.swing.JLabel lbl_obrigatorio;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_voto_opcional;
    private javax.swing.JLabel lbl_voto_proibido;
    // End of variables declaration//GEN-END:variables
}
